vanillacake369/challenge30-codingtest-study

- 임지훈-vanillacake369/Lv2/CallBy.java
- 임지훈-vanillacake369/Lv2/NoneReturningRecursive.java
- 임지훈-vanillacake369/Lv2/ReturningRecursive.java
- 임지훈-vanillacake369/Lv2/VariableScope.java
아래 4문제들을 풀어보았다. (최하단 참조)
문제 1,2,3번은 조금의 고민 이후 의사코드 작성 후 바로 풀 수 있었다. 
그런데 4번이 가장 막혔다. 거의 6시간이나 걸렸다.
이유는 내가 문제를 풀기 위한 프로세스에 대한 이해를 완벽히 하지 않은채 접근하였기 때문이다.
최소공배수를 재귀호출로 접근하는 문제였는데 소수판별을 해야한다는 이상한 접근법을 도출해냈기 때문이다.
(그냥 우리가 흔히 아는 그 접근법으로 풀면된다)
꼭 내가 생각한 프로세스가 맞는지 ***검증하는 단계를 해보고 구현해보려고*** 노력하자.
4번문제에 대해서는 노션에 저장해두었다.
https://vanillacake369.notion.site/Day-01-5f988401774445f5a531897f54174409
- Call by value/ Call by reference
- [https://www.codetree.ai/missions/5/problems/operational-values-for-two-integers-2/description](https://www.codetree.ai/missions/5/problems/operational-values-for-two-integers-2/description)
- 변수의 영역
- [https://www.codetree.ai/missions/5/problems/sum-of-specific-intervals/description](https://www.codetree.ai/missions/5/problems/sum-of-specific-intervals/description)
- 값을 …
> 임지훈 / 5월 1주차 / 4문제

- 박준영-notenoughnowjy/Lv1/PrintHelloWorld.java
- 박준영-notenoughnowjy/Lv2/callbyvalue.java
- 박준영-notenoughnowjy/Lv2/outputstar.java
- 박준영-notenoughnowjy/Lv2/rangesum.java
- 박준영-notenoughnowjy/Lv2/recursivemul.java
- 박준영-notenoughnowjy/Lv2/repeatshootingthestarsfivetimes.java
반복문을 사용하는 부분이 아직 부족하다고 느꼈으며 조금만 알고리즘이 복잡해져도 시간이 오래 소요되며, 기본기가 많이 부족하다는 느낌을 많이 받았다. 추가적으로 생각으로는 느낌이 대강 잡히는 느낌이 드는 것 같기도 한데 실제로 입력을 시작할 때는 머리가 하얗게 변하는 느낌이 있었다. 노트와 펜으로 정리를 하면서 하는 것이 좋다는 생각이 들었다.
> 박준영 / 5월 1주차 / 4문제

- 박준영-notenoughnowjy/Lv2/callbyvalue.java
- 박준영-notenoughnowjy/Lv2/output27.java
- 박준영-notenoughnowjy/Lv2/output52.java
- 박준영-notenoughnowjy/Lv2/recursivemaxvalue.java
- 박준영-notenoughnowjy/Lv2/twoequalseries.java
- 박준영-notenoughnowjy/Lv3/twoequalseries.java
이전에는 재귀함수를 이용해서 문제를 풀지 못했었는데 이번에는 재귀함수를 이용해서 문제를 풀어냈다. 확실히 하면 할수록 실력이 느는 느낌이 난다. 하지만 재귀함수 부분에 대해서는 더욱 더 공부가 필요하다고 느껴졌다. JAVA문법에 대해서는 심화적인 공부가 필요하다고 느꼈고 함수의 종류는 알지만 사용법에 대해서 잘 모른다고 느꼈다.
> Park Jun Yeong / 5월 1주차 / 4문

- 임지훈-vanillacake369/Lv2/normal_sorting/DetermineSameWord.java
- 임지훈-vanillacake369/Lv2/object/BombRemoval.java
정렬문제 중 중앙값 계산 2는 조금 헤매긴 했다.
이제 내장 함수를 이용한 정렬 문제는 조금 너무 쉽다...
이제 다만 어떤 정렬 알고리즘을 썼을 때 가장 효과적이며 어떤 식으로 알고리즘이 돌아가는지를 공부해야할 거 같다.
오늘도 코딩 화이팅
> 임지훈 / 5월 2주차 / 4문제

- 김찬유-Kimchanyoo/BombDefuse.java
- 김찬유-Kimchanyoo/CompareStrings.java
- 김찬유-Kimchanyoo/GroupByTwoMembers.java
- 김찬유-Kimchanyoo/MiddleValueCalc.java
배열과 간단한 객체문제를 풀어보았다.
배열에 대한 지식이 아직 부족한 것 같아서 ArrayList의 개념에 대해 다시 공부하였다.
이제 객체파트로 넘어가는데 객체문제에 대해 좀 더 열심히 공부해봐야할것같다
> ChanYoo Kim / 5월 2주차 / 4문제

- 박준영-notenoughnowjy/Lv3/calculatemiddlevalue.java
- 박준영-notenoughnowjy/Lv3/sequencestring.java
- 박준영-notenoughnowjy/Lv3/twogroupe.java
- 박준영-notenoughnowjy/Lv4/bombdissolution.java
이번 정렬은 첫 문제는 어려운 편이었지만 뒤의 문제는 첫번째 문제를 푼 이후라서 그런지 몰라도 비교적 쉽게 느껴졌다. 정렬에 대해서도 한번 더 공부를 해봤으면 좋겠다는 생각을 했다. 하지만 객체는 어떻게 해야할지 잘 모르는 부분이 있었다. 간단한 값을 반환받는 문제였지만, 언어 문법 구조가 생각이 안나서 꽤 애를 먹었다. 객체에 대해서 심층적인 공부가 필요하다고 생각한다.
> 박준영 / 5월 2주차 / 4문제

- 최수환-suwhan2/0508/calculateMedian2.py
- 최수환-suwhan2/0508/compareDifferentWord.py
- 최수환-suwhan2/0508/liftingBomb.py
- 최수환-suwhan2/0508/twoGroup.py
정렬, 객체
입력부, 연산부, 출력부를 나누려고 노력하면서 코딩
정렬로 풀어보고 시간 복잡도를 줄일 수 있는지 고민하며 다른 방법을 찾아보는 방식으로 진행
알게된 개념
1. 문자열이나 문자를 정렬하는 방법
2. 리스트에서 원하는 부분만 추출해서 사용하는 방법
3. 클래스를 만들어 객체를 생성하는 방법
> Suhwan Choi / 5월 2주차 / 4문제

- 이영훈-yeonghune/Lv2/DistanceFromPoint.py
- 이영훈-yeonghune/Lv2/FindLocation.py
- 이영훈-yeonghune/Lv2/LineUp.py
- 이영훈-yeonghune/Lv2/MoveInDirection.py
- 이영훈-yeonghune/Lv2/OverlappingLines.py
- 이영훈-yeonghune/Lv2/RainyDay.py
- 이영훈-yeonghune/Lv2/Return.py
- 이영훈-yeonghune/Lv2/TwoLines.py
이번에 객체정렬을 처음 풀어봅니다. 파이썬으로 클래스를 만드는데 익숙하지 않아서 어려움이 있었지만, 무사히 풀었네요 화이팅!
> 이영훈 / 5월 2주차 / 4문제

- 최수환-suwhan2/0512/comeBack.py
- 최수환-suwhan2/0512/findOverlapping.py
- 최수환-suwhan2/0512/moveDirection.py
- 최수환-suwhan2/0512/twoLine.py
dx,dy techinique , 겹치는 경우
앞의 3문제는 금방 풀었으나 마지막 모든 겹치는 선분을 찾는 문제는 푸는데 오랜시간이 걸렸다.
사실 똑똑하게 풀었다기 보다는 무식하게 풀었다. 
아직 경험이 부족한 것 같다.
더 좋은 해답을 보고 이해하며 다른 문제를 풀어보면서 사고를 넓혀야겠다.
> 최수환 / 5월 2주차 / 4문제

- 김찬유-Kimchanyoo/MeetingMoment.java
- 김찬유-Kimchanyoo/MovingRobots.java
- 김찬유-Kimchanyoo/Together.java
이번 문제는 배열 탐색과 완전 탐색에 관한 문제였다
문제의 유형자체가 생소한 나머지 문제 해결에 어려움이 있었다
2문제는 비교적 쉽게 해결했지만 로봇문제의 경우 2시간 30분이라는 시간을 투자하였지만 어느 부분이 틀렸는지 감이 잡히지 않아서 조언을 얻고자 올리게 되었고, 나머지 1문제는 시간상 문제로 올리지 못하였다
문제에 대한 공부를 좀 더 해야겠다는 생각을 하게 되었다
다음에는 조금 더 빠르고 정확하게 풀도록 노력해봐야겠다
> Chanyoo Kim / 5월 3주차 / 3문제

- 이영훈-yeonghune/Lv2/Best_Position.py
- 이영훈-yeonghune/Lv2/Gathering.py
- 이영훈-yeonghune/Lv2/MeetingMoment.py
- 이영훈-yeonghune/Lv2/MovingRobot.py
이번 문제들은 다들 구현에서 어려움이 있었다.
사용할 로직을 정하는데 어려움은 없었지만, 좌우로 움직이는 로봇과 최고의 13위치 2는 구현 난이도가 나에게는 상당했다.
특히 최고의 13위치 2는 이중리스트를 활용해서 행렬과 같은 연산을 해내야 하는 작업이다. 
이번 코테 문제들로 for문과 리스트를 다루는 기술이 약간은 좋아진것 같다.
> 이영훈 / 5월 3주차 / 4문제

- 최수환-suwhan2/0515/LRrobot.py
- 최수환-suwhan2/0515/getTogether.py
- 최수환-suwhan2/0515/max13Position2.py
- 최수환-suwhan2/0515/meetMoment.py
배열기록 , 자릿수 단위로 완전 탐색
'좌우로 움직이는 로봇' 문제를 풀지 못해 해설을 참고했다. 로직은 맞게 풀었으나 파이썬 문법에 익숙하지 않은 것 같다.
'최고의13찾기2' 문제는 통과하지 못하는 테스트 케이스를 보고 풀었는데 그 예외 케이스를 보지 않았다면 못 풀었을 것 같다.
경우의 수를 생각하는 능력을 기르자. 
고쳐야 할 점이 많이 보인 만큼 유익한 시간이었다.
> 최수환 / 5월 3주차 / 4문제

- vanillacake369/Lv2/brute_force/BestPlaceOf132.java
- vanillacake369/Lv2/brute_force/Gather.java
- vanillacake369/Lv2/simulation_II/RobotMovingFromSideToSide.java
- vanillacake369/Lv2/simulation_II/TheMomentWeMeet.java
**상태값을 미리 다 저장한 뒤** - A와 B에 대한 이동명령을 다 끝마치고 난 뒤, - A와 B를 순서에 따른 비교 
> 원래는 상태 변화함과 동시에 비교를 바로 하고 또 다음 상태변화를 하려 했다.
> > 변화 A > 비교 A > 변화 B > 비교 B >변화 C > 비교 C >변화 D > 비교 D
> 이렇게 하려고 하는 경우에는 상태변화에 대한 입력값을 최대한 잘게 조개야 한다.
> > 오른쪽 이동 3 :: 변화 1 > 비교 1 > 변화 2 > 비교 2 >변화 3 > 비교 3
> 따라서 상태변화 로직과 비교하는 로직을 아예 분리하여 해결하였다.
> > 오른쪽 이동 3 :: 변화 1 > 변화 2 >변화 3 > 비교 1 > 비교 2 > 비교 3
- 배열로 접근하다 보니 입력에 관련되지 않은 인덱스들이 0으로 초기화되어있어 비교하기가 어려웠다.
- 입력에 대한 저장구조와 상태변화에 대한 저장구조를 분리하는 게 어려웠다.
- 위 접근법을 도출하는 게 어려웠다. 습관처럼 각 변화에 따른 비교를 하려고 했기 때문이다.
문제 1번과 동일한 접근법으로 풀렸다. 다만 조건이 추가되어 그 부분만 신경써주어야 했는데 조금만 신경써주면 금방 풀리는 문제였다.
각 모든 경우의 수를 연산하여 저장한 뒤, 그 중에서 최적의 값을 찾았다.
루프 이후, 정렬을 통해 풀 수 있어 애로사항 없이 깔끔하게 풀렸다.
각 경우의 수 중 최적의 값을 추출,
그 최적의 값의 조합 중 최적의 값을 추출하는 방식으로 접근하였다.
> group A, group B, group C, ....
=> 1차 최적값 추출 필터링 :: MAX(group A), …
> 임지훈 / 5월 3주차 / 4문제

- vanillacake369/Lv2/brute_force/ARoomInACircle.java
- vanillacake369/Lv2/brute_force/AwkwardDigits2.java
- vanillacake369/Lv2/brute_force/PairParentheses2.java
자꾸 실수하는 부분이 있다.
- 조건을 잘못 읽어 헤메는 경우가 있었다. 
- > 최솟값을 최댓값이라고 읽어 푼다던지, 삼항연산자를 사용할 때 잘못써서 false일 때 실행될 걸 true쪽에 한다던지
- 여러 루프를 사용하여 모든 경우에 접근하는 방법을 어느정도는...이제 알것만 같다.
- 확실히 한 문제를 풀거나 해설코드를 보고 터득한 부분을 정리해두는 게 좋은 것 같다. 여러 루프 형성 후 base case에 대한 로직 생성하는 방법으로 접근하니 점점 익숙해져가고 있다.
> 임지훈 / 5월 3주차 / 3문제

- 최수환-suwhan2/0517/circleRoom.py
- 최수환-suwhan2/0517/parenthesis.py
- 최수환-suwhan2/0517/strangeNumber2.py
완전탐색
하나씩 경우의 수를 따지다보면 어렵지 않게 풀 수 있었다.
> 최수환 / 5월 3주차 / 3문제

- 최수환-suwhan2/0521/beautifulSequence.py
- 최수환-suwhan2/0521/maxSum.py
- 최수환-suwhan2/0521/virus.py
완전 탐색, 배열 기록
악수와 전염병의 상관관계 2 문제가 경우의 수를 체크하는 과정에서 오래 걸렸다.
연습장에 경우의 수를 적어가며 구현하니 풀 수 있었다.
이번 3 문제 모두 모든 경우의 수를 체크하는 느낌으로 풀었는데 여러 사람의 풀이를 참고하면서 생각하지 못했던 풀이 방식을 찾아 봐야겠다.
> 최수환 /  5월 3주차 / 3문제

- 이영훈-yeonghune/Lv2/BeautifulSeqNum.py
- 이영훈-yeonghune/Lv2/Handshake.py
- 이영훈-yeonghune/Lv2/MaxSumInInterval.py
아름다운 수열이랑 구간중 최대 합은 크게 어렵지 않았다.
특히 아름다운 수열을 봤을때 sorting을 하면 쉽게 풀리지 않을까 하는 추측에 들어갔는데 정답이여서 운이좋았다.
마지막으로 악수와 전염병의 상관 관계는 생각보다 쉬웠다.
사용되는 변수가 많아서 겁을 먹었는데, 이 문제 같은 경우는 문제를 읽는데 평소보다 많은 시간을 할애했다.
이런 문제는 무작정 덤비는것보다 문제 분석을 더 꼼꼼히 하라는 교훈을 얻었다.
> 5월 / 3주차 / 3문제

- vanillacake369/Lv2/brute_force/BeautifulSequence2.java
- vanillacake369/Lv2/brute_force/CorrelationBetweenShakingHandsAndInfectiousDiseases2.java
- vanillacake369/Lv2/brute_force/MaxSumOfSubarray.java
모든 인덱스에 대한 루프  안에
하나의 sub-set을 만드는 루프를 만들고
sub-set을 만들 때마다 최대값인지 검증함
x
나는 무지성 for문이 싫다.... ~그럼 우째...완탐은 다 찾는건디...~
수열 A내에서 수열 B의 모든 경우를 확인해야하므로
수열 B의 모든 경우를 만들고
수열 A가 가지고 있는지 검증함
1. 배열의 데이터들에 대해 permutation을 구하는 알고리즘 - heap's algorithm 이 어려운 건지 몰랐음 [노션 참고](https://vanillacake369.notion.site/Permutation-of-array-48e23bd558864a2ca4d37b213da488d5)
2. 이렇게 푸는 게 아니었다. 왜냐하면 **연속 부분 수열들 중에서** 라고 적혀있기 때문이다. *이 때문에 5 5 5에서 5 5의 개수는 2개이다.*
1. 조건을 무지하게 잘 읽자. 무지하게. 그냥 대충 슥하고 쇽하지 말자. 제발...
감연전파자 배열 / 최종감염 배열 / 악수이벤트 배열 로 분리한 뒤,
악수이벤트에 따라 감연전파를 실행하며 최종감염을 업데이트하는 방식으로
구현하였다.
잘 풀었다.
다만 미친것인지 **조건을 빼먹고** 풀었다.
조건에는 감염된 전적이 있는 비감염자는 이후 감염되어도 전파할 수가 없다라는 조건이 있다.
> 개발자가 이 병에 감염된 후에는 정확히 K번의 악수 동안만 전염병을 옮기게 되고, 그 이후부터는 전염병에 걸려있지만 새로 옮기지는 않게 됩니다.
해당 조건을 빼먹고 2시간 내내 뻘짓을 했다.
⚠️ 조건
⚠️ 또 조건
⚠️ 또또또또 조건
> 임지훈 / 5월 / 3주차 / 3문제

- 최수환-suwhan2/0524/developerAbility3.py
- 최수환-suwhan2/0524/lock.py
- 최수환-suwhan2/0524/specificArea2.py
완전탐색
하나씩 구현해서 풀면 금방 풀 수 있었다.
첫 문제는 수학식을 도입해 for문 없이 풀었다.
> 최수환 / 5월 4주차 / 3문제

- vanillacake369/Lv2/brute_force_1/ARoomInACircle.java
- vanillacake369/Lv2/brute_force_1/AbilityOfDeveloper3.java
- vanillacake369/Lv2/brute_force_1/AwkwardDigits2.java
- vanillacake369/Lv2/brute_force_1/BeautifulSequence2.java
- vanillacake369/Lv2/brute_force_1/BestPlaceOf132.java
- vanillacake369/Lv2/brute_force_1/CorrelationBetweenShakingHandsAndInfectiousDiseases2.java
- vanillacake369/Lv2/brute_force_1/Gather.java
- vanillacake369/Lv2/brute_force_1/MaxSumOfSubarray.java
- vanillacake369/Lv2/brute_force_1/OneWayLock.java
- vanillacake369/Lv2/brute_force_1/PairParentheses2.java
- vanillacake369/Lv2/brute_force_1/SpecificZoneAboveThe2dCoordinate2.java
- 자바로 푸는만큼, 제한시간에 맞추는 연습을 좀 해보자.
- 물론 이 문제와는 논외이지만, Mutation을 의식하는만큼 원형배열을  복사 후 정렬하는 코드를 생각하고 있자.
- 초기에 문제 이해를 잘 못 하겠었음
- 제한시간에 맞춰서 풀기가 어려웠음
- 의사코드랑 선언해야하는 객체에 시간이 좀 많이 뺏김
[문제링크](https://www.codetree.ai/missions/5/problems/ability-of-developer-3/description)
> 세 명을 루프로 뽑게 되면 나머지에 관한 연산을 수행해야 하는데 이를 "전체 - 뽑은 세명" 으로 접근함
- 위 방법보다 *더 쉽게 하는 방법*이 없을까 싶음
- 제한시간에 맞춰서 풀기가 어려웠음
- 의사코드랑 선언해야하는 객체에 시간이 좀 많이 뺏김
- 초기에 x,y 좌표를 각각 정렬하고 풀려했으나 조건 필터링 이후 넓이에 대한 최소값을 구했어야 하므로 무조건 완탐을 사용해야 함을 깨달음
- 제한시간에 맞춰서 풀기가 어려웠음
- 의사코드랑 선언해야하는 객체에 시간이 좀 많이 뺏김
> 임지훈 / 5월 4주차 / 3문제

- 김찬유-Kimchanyoo/DeveloperSkills.java
- 김찬유-Kimchanyoo/OpenLock.java
- 김찬유-Kimchanyoo/SpecificAreaOnCoordinatePlane.java
이번 문제를 해결하면서 느낀 점은 아직 JAVA문법이 부족하다는 것이다.
문제를 이해하고 로직을 구성하는 것까지 비교적 빠르게 하였지만 이를 JAVA문법을 이용해 코드로 옮기는 과정에서 시간이 걸리는 기분이 들었고, 실제로 "좌표평면 위의 특정 구역 2"를 해결하는 과정에서 로직은 정확하게 구성했지만, 틀린 표현을 사용해서 이를 고치는데만 2~30분이 걸렸다.
문법 공부 또한 소홀히 하지 않도록 해야겠다
> Chanyoo Kim / 5월 4주차 / 3문제

- 이영훈-yeonghune/Lv2/OneWayLock.py
- 이영훈-yeonghune/Lv2/ProgrammerAbility.py
- 이영훈-yeonghune/Lv2/XYRectangle.py
이번에 3문제는 그렇게 어렵지 않았다.
for문으로 안 풀려고 노력했지만, 3중 for문으로 아니면 못 푸는 문제들도 있었다.
> 이영훈 / 5월 4주차 / 3문제

- 이영훈-yeonghune/Lv2/FillInTheRec.py
- 이영훈-yeonghune/Lv2/GorH2.py
- 이영훈-yeonghune/Lv2/Teacher.py
이번에 완탐 문제는 생각보다 수월했다. 하지만 시뮬레이션 '빙빙 돌며 숫자 사각형 채우기 2' 가 힘들었다.
아직은 dx dy 테크닉에 좀 더 익수해질 필요가 있어 보인다.
> 이영훈 / 5월 5주차 / 3문제

- vanillacake369/Lv2/brute_force_2/GOrH2.java
- vanillacake369/Lv2/brute_force_2/TheGraceFormTeacher2.java
- vanillacake369/Lv2/simulation_II/SnailNumberSquare2.java
- 상황에 따라 수시로 조건이 변경됨에 따라 ***조건들을 분류하는 작업***이 어려웠다. 
> 예를 들면 방향전환해야하는 경우에 대해 두 가지로 나눌 수 있는데 다음 이동칸이 1) 배열의 끝이거나, 2) 이미 이동했던 칸이거나 이다.
- 케이스를 분류했다 하더라도, 이를 조건문을 통해 ***시뮬레이션 config들을 수시로 바꾸며 시뮬레이션을 돌리는 구현작업***이 어려웠다. 
> 다음칸에 대해 검증 후 이동하는 두 가지 케이스 
1) 다음 칸이 마지막 칸이라면 
=> 방향 전환
=> 만약 전환 후 가야하는 다음칸이 이미 갔던 칸이거나, 끝이라면 이동종료
=> 아니라면 방향 전환한 채로 이동
2) 다음 칸이 갔던 칸이라면
=> 방향 전환 후 이동
- ***특이한 예외 처리나 구현한 조건문들의 순서를 배정하는 것***을 신경쓰는 부분 - 어느 것부터 필터링해야하는지 등등 - 도 어려웠다.
> [1][1]과 같은 입력 처리
- 케이스 분류
- 어떤 시퀀스 순으로 프로세스를 처리할 것인가
- 예외 처리
- 완탐은 항상 이게 완탐인지 아닌지 모르겠다
- 여러 조건 중에 어느 것을 기준으로 두고 nested loop를 돌지를 판단하는 게 어려웠다. 
> 쿠폰을 맥인 사람을 기준으로 한 채 여러 사람들을 그룹을 지어볼지 vs 여러 사람들을 그룹 지어보며 그룹에 대해 한 명에게 쿠폰을 맥여볼지
- mutation을 피하는 정렬 방법을 찾기 어려웠다.
> 이는 이와 같은 코드로 해결하였다.
```java
int[] p = {1,329,3};
int[] pDesc = Arrays.stream(p).boxed() …
```
> 임지훈 / 5월 5주차 / 3문제

- 김태현-kthowns/lv1/play-with-array.cpp
- 김태현-kthowns/lv1/remainder-of-division.cpp
로직을 구상하고 구현하는 것은 문제없었지만 채점 기준에 맞는 출력형식을 맞추는 부분에서 실수가 있었습니다.
> Taehyeon Kim / 5월 4주차 / 3문제

- 이정빈-binedwin/lv1/369 games using functions
- 이정빈-binedwin/lv1/Minimum common multiple
함수를 이용하는 것이 아직 익숙하지 않아서 시간이 많이 걸렸습니다.
> 이정빈 / 6월 1주차 / 2문제

- 김찬유-Kimchanyoo/AddNumber.java
dx, dy방식으로 문제를 풀어보려고 노력하면서 힘들었지만 문제를 풀어가면서 좀 더 알아가게 된것같다
> Chanyoo Kim / 5월 5주차 / 1문제

- vanillacake369/Lv2/simulation_II/AddAllTheNumbersOnThePath.java
- vanillacake369/Lv4/dfs/GraphTraversal.java
[문제 링크](https://www.codetree.ai/missions/5/problems/add-all-the-numbers-on-the-path/description)
- 핵심 로직 구현은 20분 걸렸으나 예외에 대한 조건문을 잘못 선언하여 헤매었다.
```java
// 이차원 배열의 범위 안에 있는지 체크하는 함수
private static boolean isInRange(int startX, int startY, int[][] coordinates) {
// ❌. 0열에 대해서 체크하면 안 됨
/* if (startX > 0 && startX < coordinates.length 
&& startY > 0 && startY < coordinates.length) */
if (startX >= 0 && startX < coordinates.length
&& startY >= 0 && startY < coordinates.length)
return true;
return false;
}
```
- circular linked list에 대해 구현하는 것이 시간이 걸렸다. 
> 파이썬 쓰면 해결되는 부분이므로 크게 신경쓰지는 말자.
```java
// 오른쪽으로 전환
if (command.equals("L")) {
startDirection = (startDirection - 1) % 4;
if (startDirection < 0)
startDirection += 4;
}
```
- 시뮬레이션 문제들에 익숙해질만큼 많이 풀어보기!!! …
> 임지훈 / 5월 5주차 / 1문제

- 김찬유-Kimchanyoo/BubbleSort.java
정렬에 대해 배워 본 적이 없어서 이번에 버블 정렬에 대해 공부하면서 문제를 해결해보았다
문제에서 기본적인 버블 정렬로 했을 때 문제가 생긴다는 점에 대해 인식하는데 오래 걸렸고 우선순위 큐를 사용하는 방식으로 구현을 해보았다
> Chanyoo Kim / 6월 1주차/ 1문제

- vanillacake369/Lv3/bubblesort/BubbleSort.java
기본적인 버블정렬을 구현하는 것이 아닌 
우선수위 큐를 사용한 입출력을 통해 버블정렬의 형태를 맞추는 식으로 구현해주었다.
참고안은 아래에서
https://bcp0109.tistory.com/51
https://velog.io/@choco1drink/BOJ-11920-%EB%B2%84%EB%B8%94-%EC%A0%95%EB%A0%AC
> 임지훈 / 5월 1주차 / 1문제

- 최수환-suwhan2/0606/bubbleSort.py
버블정렬
문제가 버블정렬이 아니라 당황
우선순위 큐로 풀려다 실패한 케이스이다.
> 최수환 / 6월 1주차 / 1문제

- 김찬유-Kimchanyoo/SelectionSort.java
선택정렬에 대해 공부고 문제를 풀어보니 나름 쉽게 풀린것 같다
> Chanyoo Kim / 6월 1주차 / 1문제

- 김태현-kthowns/lv1/with-or-without-2021.cpp
- 김태현-kthowns/lv2/that-season-that-day.cpp
- 김태현-kthowns/lv2/with-or-without-2021.cpp
코딩테스트를 위해서는 최소 공배수, 윤년, 각 달의 마지막 날 같은 기본 개념들을 잘 숙지해둬야 할 것 같습니다.
> Taehyeon KIm / 6월 2주차 / 2문제

- vanillacake369/Lv3/selectionsort/SelectionSort.java
> 1. 한 인덱스에 대해
> 2. 나머지 인덱스와 비교하며 
> 3. min 값을 잡거나 max 값을 잡아 swap해주는 알고리즘!
**min(max) 인 인덱스를 잡을 때 자기자신이면 swap을 안 해주는 것이 키포인트이다!**
```java
for (int i = n - 1; i >= 1; i--) {
int max = i;
for (int j = i - 1; j >= 0; j--) {
if (arr[j] > arr[max])
max = j;
}
// ❗❗
if (max != i) {
int temp = arr[i];
arr[i] = arr[max];
arr[max] = temp;
}
}
```
> 임지훈 / 6월 1주차/ 1문제
